import { readFileSync } from "node:fs";
import { describe, expect, it } from "vitest";

const source = readFileSync(new URL("./GalaxyScene.tsx", import.meta.url), "utf8");

describe("galaxy radius hierarchy", () => {
  it("uses the real photo tile set instead of generated placeholders", () => {
    expect(source).toContain("const loadPhotoTextures = async");
    expect(source).toContain("photoRing = addPhotoRing(scene, photoTextures, random, shuffledTileUrls)");
    expect(source).not.toContain("createPlaceholderTexture");
    expect(source).not.toContain("shuffledTileUrls.map(() => placeholder)");
  });

  it("keeps the middle size while doubling only the compact inner particles", () => {
    expect(source).toContain("const COMPACT_ORBIT_OUTER_RADIUS = 216");
    expect(source).toContain("const MIDDLE_INNER_RADIUS = COMPACT_ORBIT_OUTER_RADIUS");
    expect(source).toContain("const MIDDLE_PARTICLE_SIZE = 2.1");
    expect(source).toContain("const middleCount = 60000");
    expect(source).toContain("const COMPACT_PARTICLE_SIZE = MIDDLE_PARTICLE_SIZE * 2");
    expect(source).toContain("const COMPACT_PARTICLE_COUNT = 9000");
    expect(source).toContain("const COMPACT_PARTICLE_OPACITY = 0.66");
    expect(source).toContain("const OUTER_COLOR_MIN_BRIGHTNESS = 1.04");
    expect(source).toContain("const compactColor = (brightness: number)");
    expect(source).toContain("const color = compactColor(COMPACT_COLOR_BRIGHTNESS)");
    expect(source).toContain("const color = compactColor(1.08)");
    expect(source).toContain("const OUTER_COLOR_VARIATION = 0.08");
    expect(source).toContain("const OUTER_DISTANCE_SATURATION_RANGE = 0.18");
    expect(source).toContain("const distanceSaturation = OUTER_COLOR_SATURATION + (1 - depthT) * OUTER_DISTANCE_SATURATION_RANGE");
    expect(source).toContain("const outerColor = (brightness: number, saturation = OUTER_COLOR_SATURATION)");
    expect(source).toContain("const color = outerColor(OUTER_COLOR_MIN_BRIGHTNESS + random() * OUTER_COLOR_VARIATION, distanceSaturation)");
    expect(source).toContain("const FORMER_MIDDLE_PARTICLE_SIZE = 0.44");
    expect(source).toContain("const OUTER_PARTICLE_SIZE = 0.44");
    expect(source).toContain("const OUTER_PARTICLE_RADIUS = 550");
    expect(source).toContain("const FINAL_CAMERA_MARGIN = 20");
    expect(source).toContain("const PULLBACK_REFERENCE_RING_RADIUS = 530");
    expect(source).toContain("const PULLBACK_REFERENCE_SCALE = OUTER_PARTICLE_RADIUS / PULLBACK_REFERENCE_RING_RADIUS");
    expect(source).toContain("const PULLBACK_REFERENCE_RADIUS = Math.hypot(30, 600) * PULLBACK_REFERENCE_SCALE");
    expect(source).toContain("const FINAL_CAMERA_RADIUS = PULLBACK_REFERENCE_RADIUS + FINAL_CAMERA_MARGIN");
    expect(source).toContain("const final = new THREE.Vector3(-200, 360, -700)");
    expect(source).toContain("const OUTER_OPACITY = 0.34");
    expect(source).toContain("const OUTER_PARTICLE_COUNT = 220000");
    expect(source).toContain("const CUBIC_STAR_COUNT = 8000");
    expect(source).toContain("const CUBIC_STAR_HALF_EXTENT = 2400");
    expect(source).toContain("cubicStars.name = \"cubic-galaxy-starfield\"");
    expect(source).toContain("const shellCount = 30000");
    expect(source).toContain("const fireflyCount = 6500");
    expect(source).toContain("const middleCount = 60000");
    expect(source).toContain("renderer.setPixelRatio(Math.min(window.devicePixelRatio, 1.2))");
    expect(source).toContain("const AURORA_POINT_COUNT = 34");
    expect(source).toContain("for (let index = 0; index < 14; index += 1)");
    expect(source).toContain("group.name = \"surrounding-soft-aurora-halo\"");
    expect(source).toContain("const line = new THREE.LineLoop(geometry, material)");
    expect(source).toContain("const color = new THREE.Color(lavender ? \"#cdb7ff\" : (random() > 0.45 ? \"#f5c9ef\" : \"#ffe2f8\"))");
    expect(source).toContain("setHSL(0.88 + random() * 0.07, 0.42, 0.66 + random() * 0.13)");
    expect(source).toContain("function addAurora(scene: THREE.Scene, random: () => number)");
    expect(source).toContain('group.name = "surrounding-soft-aurora-halo"');
    expect(source).toContain("const ribbonColors = [0xffc6f5, 0xd9b7ff, 0xffe4fb, 0xb9d8ff]");
    expect(source).toContain("opacity: 0.065 + random() * 0.045");
    expect(source).toContain("positions.setXYZ(point, Math.cos(angle) * radius");
    expect(source).not.toContain("function addMeteors");
    expect(source).toContain("const equator = new THREE.Vector3(0, 0, PULLBACK_REFERENCE_RADIUS)");
    expect(source).toContain("const cameraRadius = THREE.MathUtils.lerp(PULLBACK_REFERENCE_RADIUS, FINAL_CAMERA_RADIUS, easedRotation)");
    expect(source).toContain("const finalBloomRelief = THREE.MathUtils.lerp(1, 0.82");
    expect(source).toContain(".multiplyScalar(FINAL_CAMERA_RADIUS)");
    expect(source).toContain("const rawPullbackProgress = (t - CLOSE_IN_DURATION) / EQUATORIAL_PULLBACK_DURATION");
    expect(source).toContain("const pullbackProgress = smoother(Math.min(Math.max(rawPullbackProgress, 0), 1))");
    expect(source).toContain("const easedRotation = smoother(Math.min(Math.max(rotationProgress, 0), 1))");
    expect(source).toContain("const arcAngle = equatorDirection.angleTo(finalDirection)");
    expect(source).toContain("position = arcDirection.normalize().multiplyScalar(cameraRadius)");
    expect(source).toContain("const pullbackT = THREE.MathUtils.clamp(");
    expect(source).toContain("const portraitCompensation = 0.85 * (1 - smoother(pullbackT))");
    expect(source).toContain("const transitionBloomRelief = 1 - smoother(transitionProximity) * 0.34");
    expect(source).toContain("title.rotation.y = pose.textY + Math.sin(clock * 0.25) * 0.018");
    expect(source).toContain("title.position.y = Math.sin(clock * 0.18) * 3");
    expect(source).toContain("const closeTileScale = THREE.MathUtils.lerp(0.68, 1, closeTileProgress)");
    expect(source).toContain("const spriteScale = closeTileScale * (1 + (PHOTO_FLIGHT_SCALE - 1) * easedFlight)");
    expect(source).toContain("item.sprite.position.lerpVectors(item.base, item.target, easedFlight)");
    expect(source).toContain("item.sprite.scale.copy(item.originalScale).multiplyScalar(spriteScale)");
    expect(source).toContain("isOuter ? 1 + wideGrade * 0.42");
    expect(source).toContain("innerPositions, innerColors, COMPACT_PARTICLE_SIZE");
    expect(source).toContain("middlePositions, middleColors, MIDDLE_PARTICLE_SIZE, 0.76");
    expect(source).toContain("outerPositions, outerColors, OUTER_PARTICLE_SIZE");
  });
});
